/**
 * Spending Analyzer — LLM-powered merchant classification.
 *
 * Flow:
 *  1. Load all transactions for the user (up to 13 months)
 *  2. Group by normalized merchant key, compute per-merchant stats
 *  3. Filter out merchants already classified recently
 *  4. Send merchant profiles to OpenAI (structured output, batched ~80/call)
 *  5. Upsert results into merchant_mappings
 *  6. Return a summary with insights
 */

import { db } from '$lib/db';
import { sensorEvents, merchantMappings } from '$lib/db/schema';
import { and, eq, sql, inArray } from 'drizzle-orm';
import { openai } from '$lib/server/openai';
import { DEFAULT_USER_ID } from '$lib/server/users';

// ─── Types ───────────────────────────────────────────────────────────────────

export type MerchantProfile = {
	merchantKey: string;
	/** Example raw description from a transaction */
	exampleDescription: string;
	txCount: number;
	/** Average absolute amount per transaction (NOK) */
	avgAmount: number;
	/** Total absolute amount across all history */
	totalAmount: number;
	/** Number of distinct calendar months this merchant appeared */
	monthsActive: number;
	/** Average monthly spend (totalAmount / monthsActive) */
	avgMonthlyAmount: number;
	/** Coefficient of variation (σ / μ) — low = very regular amount, high = varies a lot */
	cv: number;
	/** Earliest and latest transaction month */
	firstMonth: string;
	lastMonth: string;
};

export type MerchantClassification = {
	merchantKey: string;
	category: string;
	subcategory: string | null;
	label: string;
	emoji: string;
	isFixed: boolean;
};

export type AnalysisResult = {
	totalMerchantsAnalyzed: number;
	totalTransactions: number;
	newMappings: number;
	updatedMappings: number;
	skippedRecent: number;
	/** Natural-language insights generated by the LLM */
	insights: string[];
	/** Top merchants by total amount */
	topMerchants: Array<{ label: string; totalAmount: number; category: string }>;
};

// ─── Constants ────────────────────────────────────────────────────────────────

const BATCH_SIZE = 50;
/** Max parallel LLM calls */
const MAX_PARALLEL = 3;
/** Re-analyze a merchant if its mapping is older than this many days */
const RECLASSIFY_AFTER_DAYS = 30;

// ─── Main entry point ─────────────────────────────────────────────────────────

export async function analyzeSpending(
	userId: string = DEFAULT_USER_ID,
	accountId?: string | null,
	forceReclassify = false
): Promise<AnalysisResult> {
	// 1. Load raw transactions (last 13 months)
	const cutoff = new Date();
	cutoff.setMonth(cutoff.getMonth() - 13);

	const where = accountId
		? and(
				eq(sensorEvents.userId, userId),
				eq(sensorEvents.dataType, 'bank_transaction'),
				sql`data->>'accountId' = ${accountId}`,
				sql`timestamp >= ${cutoff.toISOString()}`
			)
		: and(
				eq(sensorEvents.userId, userId),
				eq(sensorEvents.dataType, 'bank_transaction'),
				sql`timestamp >= ${cutoff.toISOString()}`
			);

	const rows = await db
		.select({
			timestamp: sensorEvents.timestamp,
			amount: sql<number>`(data->>'amount')::numeric`,
			description: sql<string>`data->>'description'`,
			typeText: sql<string>`data->>'category'`
		})
		.from(sensorEvents)
		.where(where);

	if (rows.length === 0) {
		return {
			totalMerchantsAnalyzed: 0,
			totalTransactions: 0,
			newMappings: 0,
			updatedMappings: 0,
			skippedRecent: 0,
			insights: ['Ingen transaksjoner funnet i perioden.'],
			topMerchants: []
		};
	}

	// 2. Group by normalized merchant key
	const profiles = buildMerchantProfiles(rows);

	// 3. Load existing mappings to detect stale ones
	const existingMappings = await db
		.select({
			merchantKey: merchantMappings.merchantKey,
			analyzedAt: merchantMappings.analyzedAt
		})
		.from(merchantMappings)
		.where(eq(merchantMappings.userId, userId));

	const existingMap = new Map(existingMappings.map((m) => [m.merchantKey, m.analyzedAt]));

	const staleThreshold = new Date();
	staleThreshold.setDate(staleThreshold.getDate() - RECLASSIFY_AFTER_DAYS);

	let skippedRecent = 0;
	const toClassify: MerchantProfile[] = [];
	for (const p of profiles) {
		const analyzedAt = existingMap.get(p.merchantKey);
		if (!forceReclassify && analyzedAt && analyzedAt > staleThreshold) {
			skippedRecent++;
		} else {
			toClassify.push(p);
		}
	}

	// 4. Classify in batches — run up to MAX_PARALLEL concurrent LLM calls
	let newMappings = 0;
	let updatedMappings = 0;
	const allClassifications: MerchantClassification[] = [];

	const batches: MerchantProfile[][] = [];
	for (let i = 0; i < toClassify.length; i += BATCH_SIZE) {
		batches.push(toClassify.slice(i, i + BATCH_SIZE));
	}

	// Process batches in parallel chunks
	for (let i = 0; i < batches.length; i += MAX_PARALLEL) {
		const chunk = batches.slice(i, i + MAX_PARALLEL);
		const results = await Promise.all(chunk.map((b) => classifyMerchantsBatch(b)));
		for (const r of results) allClassifications.push(...r);
	}

	// 5. Upsert results
	const now = new Date();
	for (const c of allClassifications) {
		const profile = profiles.find((p) => p.merchantKey === c.merchantKey);
		const isUpdate = existingMap.has(c.merchantKey);

		await db
			.insert(merchantMappings)
			.values({
				userId,
				merchantKey: c.merchantKey,
				category: c.category,
				subcategory: c.subcategory,
				label: c.label,
				emoji: c.emoji,
				isFixed: c.isFixed,
				txCount: profile?.txCount ?? 0,
				avgMonthlyAmount: profile?.avgMonthlyAmount?.toFixed(0),
				monthsActive: profile?.monthsActive ?? 0,
				source: 'ai',
				analyzedAt: now
			})
			.onConflictDoUpdate({
				target: [merchantMappings.userId, merchantMappings.merchantKey],
				set: {
					category: c.category,
					subcategory: c.subcategory,
					label: c.label,
					emoji: c.emoji,
					isFixed: c.isFixed,
					txCount: profile?.txCount ?? 0,
					avgMonthlyAmount: profile?.avgMonthlyAmount?.toFixed(0),
					monthsActive: profile?.monthsActive ?? 0,
					source: 'ai',
					analyzedAt: now,
					updatedAt: now
				}
			});

		if (isUpdate) updatedMappings++;
		else newMappings++;
	}

	// 6. Generate insights
	const allMappings = await db
		.select()
		.from(merchantMappings)
		.where(eq(merchantMappings.userId, userId));

	const mappingMap = new Map(allMappings.map((m) => [m.merchantKey, m]));

	const enrichedProfiles = profiles.map((p) => ({
		...p,
		mappedCategory: mappingMap.get(p.merchantKey)?.category ?? 'annet',
		mappedLabel: mappingMap.get(p.merchantKey)?.label ?? p.exampleDescription,
		mappedIsFixed: mappingMap.get(p.merchantKey)?.isFixed ?? false
	}));

	const insights = await generateInsights(enrichedProfiles, rows.length);

	const topMerchants = enrichedProfiles
		.filter((p) => p.totalAmount > 0)
		.sort((a, b) => b.totalAmount - a.totalAmount)
		.slice(0, 10)
		.map((p) => ({
			label: p.mappedLabel,
			totalAmount: Math.round(p.totalAmount),
			category: p.mappedCategory
		}));

	return {
		totalMerchantsAnalyzed: profiles.length,
		totalTransactions: rows.length,
		newMappings,
		updatedMappings,
		skippedRecent,
		insights,
		topMerchants
	};
}

// ─── Load all mappings for a user (for use in categorizeTransaction) ──────────

export async function loadMerchantMappings(
	userId: string
): Promise<Map<string, { category: string; subcategory: string | null; label: string; emoji: string | null; isFixed: boolean }>> {
	const rows = await db
		.select({
			merchantKey: merchantMappings.merchantKey,
			category: merchantMappings.category,
			subcategory: merchantMappings.subcategory,
			label: merchantMappings.label,
			emoji: merchantMappings.emoji,
			isFixed: merchantMappings.isFixed
		})
		.from(merchantMappings)
		.where(eq(merchantMappings.userId, userId));

	return new Map(rows.map((r) => [r.merchantKey, r]));
}

// ─── Merchant profile builder ─────────────────────────────────────────────────

function normalizeKey(description: string | null): string {
	if (!description) return 'ukjent';
	return description.toLowerCase().trim();
}

function buildMerchantProfiles(
	rows: Array<{ timestamp: Date; amount: number; description: string | null; typeText: string | null }>
): MerchantProfile[] {
	// Group by normalized key
	const groups = new Map<
		string,
		{
			exampleDescription: string;
			amounts: number[];
			months: Set<string>;
		}
	>();

	for (const row of rows) {
		const key = normalizeKey(row.description);
		const absAmount = Math.abs(Number(row.amount) || 0);
		const month = row.timestamp.toISOString().slice(0, 7);

		if (!groups.has(key)) {
			groups.set(key, {
				exampleDescription: row.description ?? 'Ukjent',
				amounts: [],
				months: new Set()
			});
		}
		const g = groups.get(key)!;
		if (absAmount > 0) g.amounts.push(absAmount);
		g.months.add(month);
	}

	const profiles: MerchantProfile[] = [];
	for (const [key, g] of groups) {
		if (g.amounts.length === 0) continue;

		const txCount = g.amounts.length;
		const totalAmount = g.amounts.reduce((a, b) => a + b, 0);
		const avgAmount = totalAmount / txCount;
		const monthsActive = g.months.size;
		const avgMonthlyAmount = totalAmount / monthsActive;

		// Coefficient of variation
		const variance =
			g.amounts.reduce((sum, a) => sum + Math.pow(a - avgAmount, 2), 0) / txCount;
		const stdDev = Math.sqrt(variance);
		const cv = avgAmount > 0 ? stdDev / avgAmount : 0;

		const sortedMonths = Array.from(g.months).sort();

		profiles.push({
			merchantKey: key,
			exampleDescription: g.exampleDescription,
			txCount,
			avgAmount: Math.round(avgAmount),
			totalAmount: Math.round(totalAmount),
			monthsActive,
			avgMonthlyAmount: Math.round(avgMonthlyAmount),
			cv: Math.round(cv * 100) / 100,
			firstMonth: sortedMonths[0],
			lastMonth: sortedMonths[sortedMonths.length - 1]
		});
	}

	return profiles.sort((a, b) => b.totalAmount - a.totalAmount);
}

// ─── LLM: classify a batch of merchants ───────────────────────────────────────

const FEW_SHOT_EXAMPLES = [
	{
		merchantKey: 'ruter as oslo',
		exampleDescription: 'Ruter AS Oslo',
		txCount: 24,
		avgAmount: 320,
		monthsActive: 12,
		cv: 0.85
	},
	{
		merchantKey: 'obos boligselskap',
		exampleDescription: 'OBOS Boligselskap',
		txCount: 12,
		avgAmount: 4200,
		monthsActive: 12,
		cv: 0.02
	},
	{
		merchantKey: 'sb1 terminbeløp huslån',
		exampleDescription: 'SB1 Terminbeløp Huslån',
		txCount: 12,
		avgAmount: 12500,
		monthsActive: 12,
		cv: 0.01
	},
	{
		merchantKey: 'if skadeforsikring bil',
		exampleDescription: 'IF Skadeforsikring Bil',
		txCount: 12,
		avgAmount: 640,
		monthsActive: 12,
		cv: 0.0
	},
	{
		merchantKey: 'grorud aks',
		exampleDescription: 'Grorud AKS',
		txCount: 10,
		avgAmount: 750,
		monthsActive: 10,
		cv: 0.03
	},
	{
		merchantKey: 'bjørnsletta barnehage',
		exampleDescription: 'Bjørnsletta Barnehage',
		txCount: 11,
		avgAmount: 3400,
		monthsActive: 11,
		cv: 0.05
	},
	{
		merchantKey: 'svømmeklubben oslo svømmekurs',
		exampleDescription: 'Svømmeklubben Oslo Svømmekurs',
		txCount: 8,
		avgAmount: 800,
		monthsActive: 8,
		cv: 0.0
	},
	{
		merchantKey: 'kiwi 123 oslo sentrum',
		exampleDescription: 'Kiwi 123 Oslo Sentrum',
		txCount: 48,
		avgAmount: 450,
		monthsActive: 12,
		cv: 0.7
	},
	{
		merchantKey: 'maxbo alnabru',
		exampleDescription: 'Maxbo Alnabru',
		txCount: 8,
		avgAmount: 1200,
		monthsActive: 4,
		cv: 0.85
	},
	{
		merchantKey: 'elektriker as faktura',
		exampleDescription: 'Elektriker AS Faktura',
		txCount: 3,
		avgAmount: 4500,
		monthsActive: 2,
		cv: 0.4
	},
	{
		merchantKey: 'fremtind forsikring sykkel',
		exampleDescription: 'Fremtind Forsikring Sykkel',
		txCount: 12,
		avgAmount: 89,
		monthsActive: 12,
		cv: 0.01
	}
] as const;

const FEW_SHOT_OUTPUTS: MerchantClassification[] = [
	{ merchantKey: 'ruter as oslo', category: 'transport', subcategory: 'kollektivtransport', label: 'Ruter – kollektivtransport', emoji: '🚇', isFixed: false },
	{ merchantKey: 'obos boligselskap', category: 'bolig', subcategory: 'husleie/fellesutgifter', label: 'OBOS – boligselskap', emoji: '🏠', isFixed: true },
	{ merchantKey: 'sb1 terminbeløp huslån', category: 'lån', subcategory: 'huslån', label: 'Sparebank 1 – huslån', emoji: '🏦', isFixed: true },
	{ merchantKey: 'if skadeforsikring bil', category: 'forsikring', subcategory: 'bilforsikring', label: 'IF Skadeforsikring – bil', emoji: '🛡️', isFixed: true },
	{ merchantKey: 'grorud aks', category: 'barn', subcategory: 'aks', label: 'Grorud AKS – aktivitetsskole', emoji: '🎒', isFixed: true },
	{ merchantKey: 'bjørnsletta barnehage', category: 'barn', subcategory: 'barnehage', label: 'Bjørnsletta Barnehage', emoji: '👶', isFixed: true },
	{ merchantKey: 'svømmeklubben oslo svømmekurs', category: 'barn', subcategory: 'svømmekurs', label: 'Svømmeklubben – svømmekurs', emoji: '🏊', isFixed: true },
	{ merchantKey: 'kiwi 123 oslo sentrum', category: 'dagligvare', subcategory: null, label: 'Kiwi', emoji: '🛒', isFixed: false },
	{ merchantKey: 'maxbo alnabru', category: 'shopping', subcategory: 'bygg og hage', label: 'Maxbo – byggevarer', emoji: '🔨', isFixed: false },
	{ merchantKey: 'elektriker as faktura', category: 'shopping', subcategory: 'håndverkere', label: 'Elektriker AS', emoji: '⚡', isFixed: false },
	{ merchantKey: 'fremtind forsikring sykkel', category: 'forsikring', subcategory: 'sykkelforsikring', label: 'Fremtind – sykkelforsikring', emoji: '🛡️', isFixed: true }
];

async function classifyMerchantsBatch(
	batch: MerchantProfile[]
): Promise<MerchantClassification[]> {
	const systemPrompt = `Du er en Norwegian bank transaction classifier. 
Din jobb er å klassifisere handlende/mottakere fra norske banktransaksjoner i kategorier og underkategorier.

Tilgjengelige kategorier (bruk kun disse):
- dagligvare (mat fra butikk)
- mat (restaurant, takeaway, kafe)
- bolig (husleie, strøm, felleskostnader, internett hjemme)
- lån (huslån, billån, forbrukslån, studielån, rammelån, terminbeløp)
- transport (kollektivtransport, drivstoff, parkering, bompenger, elbillading, fly, taxi)
- helse (lege, tannlege, apotek, fysioterapi)
- abonnement (streaming, mobilabonnement, software, magasin)
- underholdning (kino, konserter, gym, sport)
- shopping (klær, elektronikk, møbler, byggevarer, håndverkere)
- barn (barnehage, aks, sfo, svømmekurs, idrettslag, kulturskole)
- forsikring (bilforsikring, innboforsikring, reiseforsikring, sykkelforsikring, livsforsikring)
- sparing (sparekontoer, fond, aksjer)
- overføring (Vipps, overføringer til konti)
- lønn (inntekt, lønn, NAV-ytelser)
- annet (alt som ikke passer)

Regler:
- isFixed = true hvis betalingen er periodisk/fast (samme beløp, samme mottaker, månedlig/kvartal)
- Lav cv (< 0.15) + høy monthsActive = typisk fast utgift
- Lag et kort, menneskelesbart label på norsk
- subcategory er valgfri men bidrar til bedre innsikt (f.eks. "huslån", "barnehage", "bilforsikring")`.trim();

	const fewShotInput = JSON.stringify(FEW_SHOT_EXAMPLES, null, 0);
	const fewShotOutput = JSON.stringify({ classifications: FEW_SHOT_OUTPUTS }, null, 0);

	const userPrompt = `Klassifiser disse handlende/mottakerne:
${JSON.stringify(
	batch.map((p) => ({
		merchantKey: p.merchantKey,
		exampleDescription: p.exampleDescription,
		txCount: p.txCount,
		avgAmount: p.avgAmount,
		monthsActive: p.monthsActive,
		cv: p.cv
	})),
	null,
	0
)}

Returner JSON med ett objekt per handlende i samma rekkefølge:
{ "classifications": [{ "merchantKey", "category", "subcategory", "label", "emoji", "isFixed" }, ...] }`;

	const response = await openai.chat.completions.create({
		model: 'gpt-4o-mini',
		response_format: { type: 'json_object' },
		messages: [
			{ role: 'system', content: systemPrompt },
			{ role: 'user', content: fewShotInput },
			{ role: 'assistant', content: fewShotOutput },
			{ role: 'user', content: userPrompt }
		],
		temperature: 0.1,
		max_tokens: 4000
	});

	const raw = response.choices[0]?.message?.content ?? '{}';
	let parsed: { classifications?: MerchantClassification[] };
	try {
		parsed = JSON.parse(raw);
	} catch {
		console.error('[spending-analyzer] Failed to parse LLM response:', raw);
		return [];
	}

	return (parsed.classifications ?? []).filter(
		(c) => c.merchantKey && c.category && c.label
	);
}

// ─── LLM: generate human-readable insights ───────────────────────────────────

async function generateInsights(
	profiles: Array<{
		merchantKey: string;
		exampleDescription: string;
		totalAmount: number;
		avgMonthlyAmount: number;
		txCount: number;
		monthsActive: number;
		cv: number;
		firstMonth: string;
		lastMonth: string;
		mappedCategory: string;
		mappedLabel: string;
		mappedIsFixed: boolean;
	}>,
	totalTxCount: number
): Promise<string[]> {
	// Build a compact summary for the LLM
	const fixedTotal = profiles.filter((p) => p.mappedIsFixed).reduce((s, p) => s + p.totalAmount, 0);
	const variableTotal = profiles.filter((p) => !p.mappedIsFixed).reduce((s, p) => s + p.totalAmount, 0);

	// Top 20 by total amount for insight context
	const top20 = profiles.slice(0, 20).map((p) => ({
		label: p.mappedLabel,
		category: p.mappedCategory,
		totalAmount: p.totalAmount,
		avgMonthly: p.avgMonthlyAmount,
		txCount: p.txCount,
		monthsActive: p.monthsActive,
		isFixed: p.mappedIsFixed
	}));

	const prompt = `Analyser disse norske banktransaksjonsdataene og generer 4-6 korte, konkrete innsikter på norsk.

Totalt ${totalTxCount} transaksjoner. Faste utgifter: ${Math.round(fixedTotal / 1000)}k NOK. Variable: ${Math.round(variableTotal / 1000)}k NOK.

Topp mottakere (siste 13 mnd):
${JSON.stringify(top20, null, 0)}

Regler for innsikter:
- Nevn konkrete tall i NOK
- Identifiser mønstre som prosjekter, sesongvariasjoner, uvanlige utgifter
- Vurder "faste vs variable"-balansen
- Legg merke til om noen kategorier dominerer uventet
- Hvert punkt skal starte med en emoji
- Maks 1 setning per punkt

Returner JSON: { "insights": ["...", "...", ...] }`;

	try {
		const response = await openai.chat.completions.create({
			model: 'gpt-4o-mini',
			response_format: { type: 'json_object' },
			messages: [{ role: 'user', content: prompt }],
			temperature: 0.4,
			max_tokens: 600
		});

		const raw = response.choices[0]?.message?.content ?? '{}';
		const parsed = JSON.parse(raw);
		return parsed.insights ?? [];
	} catch (e) {
		console.error('[spending-analyzer] Insights generation failed:', e);
		return [];
	}
}
