/**
 * Spending Analyzer — LLM-powered merchant classification.
 *
 * Flow:
 *  1. Load all transactions for the user (up to 13 months)
 *  2. Group by normalized merchant key, compute per-merchant stats
 *  3. Filter out merchants already classified recently
 *  4. Send merchant profiles to OpenAI (structured output, batched ~80/call)
 *  5. Upsert results into merchant_mappings
 *  6. Return a summary with insights
 */

import { db } from '$lib/db';
import { sensorEvents, merchantMappings } from '$lib/db/schema';
import { and, eq, sql, inArray } from 'drizzle-orm';
import { openai } from '$lib/server/openai';
import { DEFAULT_USER_ID } from '$lib/server/users';

// ─── Types ───────────────────────────────────────────────────────────────────

export type MerchantProfile = {
	merchantKey: string;
	/** Example raw description from a transaction */
	exampleDescription: string;
	txCount: number;
	/** Average absolute amount per transaction (NOK) */
	avgAmount: number;
	/** Total absolute amount across all history */
	totalAmount: number;
	/** Number of distinct calendar months this merchant appeared */
	monthsActive: number;
	/** Average monthly spend (totalAmount / monthsActive) */
	avgMonthlyAmount: number;
	/** Coefficient of variation (σ / μ) — low = very regular amount, high = varies a lot */
	cv: number;
	/** Earliest and latest transaction month */
	firstMonth: string;
	lastMonth: string;
};

export type MerchantClassification = {
	merchantKey: string;
	category: string;
	subcategory: string | null;
	label: string;
	emoji: string;
	isFixed: boolean;
};

export type ClassificationResult = {
	totalMerchantsAnalyzed: number;
	totalTransactions: number;
	newMappings: number;
	updatedMappings: number;
	skippedRecent: number;
};

export type InsightsResult = {
	/** Natural-language insights generated by the LLM */
	insights: string[];
	/** Top merchants by total amount */
	topMerchants: Array<{ label: string; totalAmount: number; category: string }>;
};

export type AnalysisResult = ClassificationResult & InsightsResult;

// ─── Constants ────────────────────────────────────────────────────────────────

const BATCH_SIZE = 50;
/** Max parallel LLM calls */
const MAX_PARALLEL = 3;
/** Re-analyze a merchant if its mapping is older than this many days */
const RECLASSIFY_AFTER_DAYS = 30;

// ─── Main entry points ────────────────────────────────────────────────────────

/**
 * Classify merchants using LLM (OpenAI).
 * Does NOT generate insights - use generateSpendingInsights() separately for that.
 */
export async function analyzeSpending(
	userId: string = DEFAULT_USER_ID,
	accountId?: string | null,
	forceReclassify = false,
	testLimit?: number
): Promise<ClassificationResult> {
	const t0 = Date.now();
	console.log(`[analyzeSpending] Starting - testLimit: ${testLimit}, force: ${forceReclassify}`);

	const cutoff = new Date();
	cutoff.setMonth(cutoff.getMonth() - 13);

	// 1. Load existing mappings first (small query)
	const existingMappings = await db
		.select({ merchantKey: merchantMappings.merchantKey, analyzedAt: merchantMappings.analyzedAt })
		.from(merchantMappings)
		.where(eq(merchantMappings.userId, userId));

	const existingMap = new Map(existingMappings.map((m) => [m.merchantKey, m.analyzedAt]));
	console.log(`[analyzeSpending] ${existingMap.size} existing mappings in ${Date.now() - t0}ms`);

	const staleThreshold = new Date();
	staleThreshold.setDate(staleThreshold.getDate() - RECLASSIFY_AFTER_DAYS);

	// 2. Load raw transactions
	const where = accountId
		? and(
				eq(sensorEvents.userId, userId),
				eq(sensorEvents.dataType, 'bank_transaction'),
				sql`data->>'accountId' = ${accountId}`,
				sql`timestamp >= ${cutoff.toISOString()}`
			)
		: and(
				eq(sensorEvents.userId, userId),
				eq(sensorEvents.dataType, 'bank_transaction'),
				sql`timestamp >= ${cutoff.toISOString()}`
			);

	const rows = await db
		.select({
			timestamp: sensorEvents.timestamp,
			amount: sql<number>`(data->>'amount')::numeric`,
			description: sql<string>`data->>'description'`,
			typeText: sql<string>`data->>'category'`
		})
		.from(sensorEvents)
		.where(where);

	console.log(`[analyzeSpending] Loaded ${rows.length} transactions in ${Date.now() - t0}ms`);

	if (rows.length === 0) {
		return { totalMerchantsAnalyzed: 0, totalTransactions: 0, newMappings: 0, updatedMappings: 0, skippedRecent: 0 };
	}

	// 3. Resolve raw descriptions → canonical merchant keys via prefix-grouping (no LLM)
	const allDescriptions = rows.map((r) => r.description).filter(Boolean) as string[];
	const keyMap = resolveDescriptionKeysSync(allDescriptions);
	console.log(`[analyzeSpending] Key resolution done in ${Date.now() - t0}ms, ${keyMap.size} unique descriptions mapped`);

	// 4. Build merchant profiles using resolved keys
	const profiles = buildMerchantProfiles(rows, keyMap);
	console.log(`[analyzeSpending] Built ${profiles.length} merchant profiles`);

	// 5. Filter out recently analyzed merchants
	let skippedRecent = 0;
	const toClassify: MerchantProfile[] = [];
	for (const p of profiles) {
		const analyzedAt = existingMap.get(p.merchantKey);
		if (!forceReclassify && analyzedAt && analyzedAt > staleThreshold) {
			skippedRecent++;
		} else {
			toClassify.push(p);
		}
	}

	// 6. Apply test limit
	if (testLimit && testLimit > 0 && toClassify.length > testLimit) {
		console.log(`[analyzeSpending] Test mode: ${toClassify.length} → ${testLimit}`);
		skippedRecent += toClassify.length - testLimit;
		toClassify.splice(testLimit);
	}

	console.log(`[analyzeSpending] To classify: ${toClassify.length}, skipped recent: ${skippedRecent}`);

	if (toClassify.length === 0) {
		return { totalMerchantsAnalyzed: profiles.length, totalTransactions: rows.length, newMappings: 0, updatedMappings: 0, skippedRecent };
	}

	// 7. Classify in batches
	const allClassifications: MerchantClassification[] = [];
	const batches: MerchantProfile[][] = [];
	for (let i = 0; i < toClassify.length; i += BATCH_SIZE) {
		batches.push(toClassify.slice(i, i + BATCH_SIZE));
	}

	console.log(`[analyzeSpending] Sending ${batches.length} batch(es) to classification LLM...`);
	const t1 = Date.now();
	for (let i = 0; i < batches.length; i += MAX_PARALLEL) {
		const chunk = batches.slice(i, i + MAX_PARALLEL);
		const results = await Promise.all(chunk.map((b) => classifyMerchantsBatch(b)));
		for (const r of results) allClassifications.push(...r);
	}
	console.log(`[analyzeSpending] LLM classification: ${Date.now() - t1}ms, ${allClassifications.length} results`);

	// 8. Upsert results
	const t2 = Date.now();
	let newMappings = 0;
	let updatedMappings = 0;
	const now = new Date();

	for (const c of allClassifications) {
		const profile = toClassify.find((p) => p.merchantKey === c.merchantKey);
		const isUpdate = existingMap.has(c.merchantKey);

		await db
			.insert(merchantMappings)
			.values({
				userId,
				merchantKey: c.merchantKey,
				category: c.category,
				subcategory: c.subcategory,
				label: c.label,
				emoji: c.emoji,
				isFixed: c.isFixed,
				txCount: profile?.txCount ?? 0,
				avgMonthlyAmount: profile?.avgMonthlyAmount?.toFixed(0),
				monthsActive: profile?.monthsActive ?? 0,
				source: 'ai',
				analyzedAt: now
			})
			.onConflictDoUpdate({
				target: [merchantMappings.userId, merchantMappings.merchantKey],
				set: {
					category: c.category,
					subcategory: c.subcategory,
					label: c.label,
					emoji: c.emoji,
					isFixed: c.isFixed,
					txCount: profile?.txCount ?? 0,
					avgMonthlyAmount: profile?.avgMonthlyAmount?.toFixed(0),
					monthsActive: profile?.monthsActive ?? 0,
					source: 'ai',
					analyzedAt: now,
					updatedAt: now
				}
			});

		if (isUpdate) updatedMappings++;
		else newMappings++;
	}
	console.log(`[analyzeSpending] DB upsert: ${Date.now() - t2}ms | Total: ${Date.now() - t0}ms`);

	return {
		totalMerchantsAnalyzed: profiles.length,
		totalTransactions: rows.length,
		newMappings,
		updatedMappings,
		skippedRecent
	};
}

/**
 * Generate spending insights from existing merchant mappings.
 * This is separate from classification so insights can be regenerated without re-classifying.
 */
export async function generateSpendingInsights(
	userId: string = DEFAULT_USER_ID,
	accountId?: string | null
): Promise<InsightsResult> {
	// 1. Load transactions (same period as analyzeSpending)
	const cutoff = new Date();
	cutoff.setMonth(cutoff.getMonth() - 13);

	const where = accountId
		? and(
				eq(sensorEvents.userId, userId),
				eq(sensorEvents.dataType, 'bank_transaction'),
				sql`data->>'accountId' = ${accountId}`,
				sql`timestamp >= ${cutoff.toISOString()}`
			)
		: and(
				eq(sensorEvents.userId, userId),
				eq(sensorEvents.dataType, 'bank_transaction'),
				sql`timestamp >= ${cutoff.toISOString()}`
			);

	const rows = await db
		.select({
			timestamp: sensorEvents.timestamp,
			amount: sql<number>`(data->>'amount')::numeric`,
			description: sql<string>`data->>'description'`,
			typeText: sql<string>`data->>'category'`
		})
		.from(sensorEvents)
		.where(where);

	if (rows.length === 0) {
		return {
			insights: ['Ingen transaksjoner funnet i perioden.'],
			topMerchants: []
		};
	}

	// 2. Build profiles and enrich with mappings
	const insightDescriptions = rows.map((r) => r.description).filter(Boolean) as string[];
	const insightKeyMap = resolveDescriptionKeysSync(insightDescriptions);
	const profiles = buildMerchantProfiles(rows, insightKeyMap);

	const allMappings = await db
		.select()
		.from(merchantMappings)
		.where(eq(merchantMappings.userId, userId));

	const mappingMap = new Map(allMappings.map((m) => [m.merchantKey, m]));

	const enrichedProfiles = profiles.map((p) => ({
		...p,
		mappedCategory: mappingMap.get(p.merchantKey)?.category ?? 'ukategorisert',
		mappedLabel: mappingMap.get(p.merchantKey)?.label ?? p.exampleDescription,
		mappedIsFixed: mappingMap.get(p.merchantKey)?.isFixed ?? false
	}));

	// 3. Generate insights
	const insights = await generateInsights(enrichedProfiles, rows.length);

	// 4. Calculate top merchants
	const topMerchants = enrichedProfiles
		.filter((p) => p.totalAmount > 0)
		.sort((a, b) => b.totalAmount - a.totalAmount)
		.slice(0, 10)
		.map((p) => ({
			label: p.mappedLabel,
			totalAmount: Math.round(p.totalAmount),
			category: p.mappedCategory
		}));

	return {
		insights,
		topMerchants
	};
}

// ─── Load all mappings for a user (for use in categorizeTransaction) ──────────

export async function loadMerchantMappings(
	userId: string
): Promise<Map<string, { category: string; subcategory: string | null; label: string; emoji: string | null; isFixed: boolean }>> {
	const rows = await db
		.select({
			merchantKey: merchantMappings.merchantKey,
			category: merchantMappings.category,
			subcategory: merchantMappings.subcategory,
			label: merchantMappings.label,
			emoji: merchantMappings.emoji,
			isFixed: merchantMappings.isFixed
		})
		.from(merchantMappings)
		.where(eq(merchantMappings.userId, userId));

	return new Map(rows.map((r) => [r.merchantKey, r]));
}

// ─── Merchant key resolution via prefix-grouping + LLM ───────────────────────

/**
 * Resolves raw transaction descriptions to canonical merchant keys.
 *
 * Algorithm:
 * 1. Sort unique descriptions alphabetically — same merchants cluster together
 * 2. Greedy prefix-grouping: group consecutive descriptions only when they share
 *    BOTH ≥5 chars AND ≥2 complete words from the left.
 *    The 2-word requirement prevents false groupings like
 *    "BØLER BAD" + "BØLER ZOO" or "HOTEL BRISTOL" + "HOTEL INDIGO".
 * 3. The shared prefix (cleaned of trailing noise) becomes the canonical key.
 */
function resolveDescriptionKeysSync(descriptions: string[]): Map<string, string> {
	const unique = [...new Set(descriptions.map((d) => d.trim()).filter(Boolean))].sort();
	const keyMap = new Map<string, string>();

	let i = 0;
	while (i < unique.length) {
		const seed = unique[i];
		const members = [seed];
		let prefix = seed;
		let j = i + 1;
		while (j < unique.length) {
			const cp = sharedPrefix(prefix, unique[j]);
			if (cp.length >= 5 && sharedWordCount(prefix, unique[j]) >= 2) {
				members.push(unique[j]);
				prefix = cp;
				j++;
			} else {
				break;
			}
		}
		const canonicalKey = cleanKey(prefix);
		for (const member of members) {
			keyMap.set(member, canonicalKey);
		}
		i = j;
	}

	return keyMap;
}

function sharedPrefix(a: string, b: string): string {
	let i = 0;
	while (i < a.length && i < b.length && a[i] === b[i]) i++;
	return a.slice(0, i);
}

/** Count complete words shared from the left between two strings. */
function sharedWordCount(a: string, b: string): number {
	const raw = sharedPrefix(a, b); // may end with a trailing space
	const trimmed = raw.trimEnd();
	if (!trimmed) return 0;
	const words = trimmed.split(/\s+/).filter(Boolean);
	// If raw ended with whitespace, or covers all of either string → clean word boundary
	const atBoundary = raw !== trimmed || raw.length === a.length || raw.length === b.length;
	return atBoundary ? words.length : Math.max(0, words.length - 1);
}

/** Lowercase + strip trailing digits/dates/punctuation that are transaction noise */
function cleanKey(raw: string): string {
	return raw
		.toLowerCase()
		.trim()
		.replace(/[\s\d\-./*]+$/, '') // trailing dates, numbers, separators
		.trim();
}

// ─── Merchant profile builder ─────────────────────────────────────────────────

function buildMerchantProfiles(
	rows: Array<{ timestamp: Date; amount: number; description: string | null; typeText: string | null }>,
	keyMap: Map<string, string>
): MerchantProfile[] {
	const groups = new Map<
		string,
		{
			exampleDescription: string;
			amounts: number[];
			months: Set<string>;
		}
	>();

	for (const row of rows) {
		const rawDesc = row.description?.trim() ?? '';
		const key = (rawDesc ? keyMap.get(rawDesc) : null) ?? (rawDesc.toLowerCase().trim() || 'ukjent');
		const absAmount = Math.abs(Number(row.amount) || 0);
		const month = row.timestamp.toISOString().slice(0, 7);

		if (!groups.has(key)) {
			groups.set(key, { exampleDescription: row.description ?? 'Ukjent', amounts: [], months: new Set() });
		}
		const g = groups.get(key)!;
		if (absAmount > 0) g.amounts.push(absAmount);
		g.months.add(month);
	}

	const profiles: MerchantProfile[] = [];
	for (const [key, g] of groups) {
		if (g.amounts.length === 0) continue;

		const txCount = g.amounts.length;
		const totalAmount = g.amounts.reduce((a, b) => a + b, 0);
		const avgAmount = totalAmount / txCount;
		const monthsActive = g.months.size;
		const avgMonthlyAmount = totalAmount / monthsActive;

		// Coefficient of variation
		const variance =
			g.amounts.reduce((sum, a) => sum + Math.pow(a - avgAmount, 2), 0) / txCount;
		const stdDev = Math.sqrt(variance);
		const cv = avgAmount > 0 ? stdDev / avgAmount : 0;

		const sortedMonths = Array.from(g.months).sort();

		profiles.push({
			merchantKey: key,
			exampleDescription: g.exampleDescription,
			txCount,
			avgAmount: Math.round(avgAmount),
			totalAmount: Math.round(totalAmount),
			monthsActive,
			avgMonthlyAmount: Math.round(avgMonthlyAmount),
			cv: Math.round(cv * 100) / 100,
			firstMonth: sortedMonths[0],
			lastMonth: sortedMonths[sortedMonths.length - 1]
		});
	}

	return profiles.sort((a, b) => b.totalAmount - a.totalAmount);
}

// ─── LLM: classify a batch of merchants ───────────────────────────────────────

async function classifyMerchantsBatch(
	batch: MerchantProfile[]
): Promise<MerchantClassification[]> {
	const systemPrompt = `Du er en Norwegian bank transaction classifier basert på SpareBank1 sin taksonomi.
Din jobb er å klassifisere handlende/mottakere i kategorier og underkategorier.

TILGJENGELIGE KATEGORIER (bruk key-verdiene):
1. innskudd (Inntekter): lonn, utbytte, annet_innskudd
2. dagligvarer (Dagligvarer): dagligvarer, andre_dagligvarer
3. kafe_og_restaurant: fastfood, godteri, kafe, kantine, kiosk, restaurant, utesteder
4. faste_boutgifter: alarm, boligutgifter, eiendomsforvaltning, internett, kommunale_avgifter, mobiltelefon, stroem, utleie_og_salg, boliglan, boligforsikring
5. annet_lan_og_gjeld: betalingsoppfolging, lan, studielan
6. bil_og_transport: bilavgifter, bildeler_og_pleie, bilforhandler, bom, drivstoff, kollektivtransport, leiebil, parkering, taxi, trafikkskole, verksted
7. helse_og_velvaere: apotek, briller_og_opptikk, helsekost, lege, skjonnhet, tannlege, velvare
8. medier_og_underholdning: apper_og_spill, aviser, bokhandler, pengespill, strommetjenester, tidsskrifter, tv
9. hobby_og_fritid: arrangement, dating, digital_markedsplass, dyr, foto, fritidsaktiviteter, gavekort, hobby, hytte, kino, leker, museum, nettjenester, post, trening, lan_hobby_fritidsutstyr
10. hjem_og_hage: byggvare, hage_og_blomster, handverker, hvitevarer_og_elektronikk, kjokkenutstyr, mobler_og_interior, verktoy
11. klaer_og_utstyr: klaer, sko, smykker, sportsutstyr
12. barn: barnebutikker, annet_til_barna
13. barnehage_og_sfo: barnehager, sfo
14. forsikring: forsikring
15. bilforsikring_og_billan: bilforsikring, billan
16. sparing: sparing
17. reise: annen_reise, flybilletter, overnatting, reiseselskap
18. diverse: bankboks, betaling, kredittkort, krypto_epenger, kurs_utdanning, medlemskap_veldedighet, minibank, overforing, renter_innskudd, renter_og_gebyrer, skatt, vennebetaling, andre_utgifter, gave, utlegg_og_refusjon
19. ukategorisert: annet

REGLER:
- category = hovedkategori key (f.eks. "faste_boutgifter")
- subcategory = underkategori key (f.eks. "stroem") eller null
- isFixed = true hvis betalingen er periodisk/fast (samme beløp, samme mottaker, månedlig)
  * Lav cv (< 0.15) + høy monthsActive (>= 8) = typisk fast utgift
- label = kort, menneskelesbart navn på norsk (f.eks. "Fjordkraft – strøm")
- emoji = passende emoji som matcher kategorien og merchant-typen

VIKTIG: Bruk kun kategoriene og subcategories listet over!`.trim();

	const fewShotInput = JSON.stringify([
		{ merchantKey: 'ruter as oslo', exampleDescription: 'Ruter AS Oslo', txCount: 24, avgAmount: 320, monthsActive: 12, cv: 0.85 },
		{ merchantKey: 'obos boligselskap', exampleDescription: 'OBOS Boligselskap', txCount: 12, avgAmount: 4200, monthsActive: 12, cv: 0.02 },
		{ merchantKey: 'sb1 terminbeløp huslån', exampleDescription: 'SB1 Terminbeløp Huslån', txCount: 12, avgAmount: 12500, monthsActive: 12, cv: 0.01 },
		{ merchantKey: 'if skadeforsikring bil', exampleDescription: 'IF Skadeforsikring Bil', txCount: 12, avgAmount: 640, monthsActive: 12, cv: 0.0 },
		{ merchantKey: 'bjørnsletta barnehage', exampleDescription: 'Bjørnsletta Barnehage', txCount: 11, avgAmount: 3400, monthsActive: 11, cv: 0.05 },
		{ merchantKey: 'kiwi 123 oslo sentrum', exampleDescription: 'Kiwi 123 Oslo Sentrum', txCount: 48, avgAmount: 450, monthsActive: 12, cv: 0.7 },
		{ merchantKey: 'amedia produkt og teknologi as', exampleDescription: 'AMEDIA Produkt og Teknologi AS', txCount: 12, avgAmount: 45000, monthsActive: 12, cv: 0.01 }
	], null, 0);

	const fewShotOutput = JSON.stringify({ 
		classifications: [
			{ merchantKey: 'ruter as oslo', category: 'bil_og_transport', subcategory: 'kollektivtransport', label: 'Ruter – kollektivtransport', emoji: '🚇', isFixed: false },
			{ merchantKey: 'obos boligselskap', category: 'faste_boutgifter', subcategory: 'boligutgifter', label: 'OBOS – felleskostnader', emoji: '🏠', isFixed: true },
			{ merchantKey: 'sb1 terminbeløp huslån', category: 'faste_boutgifter', subcategory: 'boliglan', label: 'Sparebank 1 – boliglån', emoji: '🏦', isFixed: true },
			{ merchantKey: 'if skadeforsikring bil', category: 'bilforsikring_og_billan', subcategory: 'bilforsikring', label: 'IF – bilforsikring', emoji: '🛡️', isFixed: true },
			{ merchantKey: 'bjørnsletta barnehage', category: 'barnehage_og_sfo', subcategory: 'barnehager', label: 'Bjørnsletta Barnehage', emoji: '👶', isFixed: true },
			{ merchantKey: 'kiwi 123 oslo sentrum', category: 'dagligvarer', subcategory: 'dagligvarer', label: 'Kiwi – dagligvarer', emoji: '🛒', isFixed: false },
			{ merchantKey: 'amedia produkt og teknologi as', category: 'innskudd', subcategory: 'lonn', label: 'Amedia – lønn', emoji: '💵', isFixed: true }
		]
	}, null, 0);

	const userPrompt = `Klassifiser disse handlende/mottakerne:
${JSON.stringify(
	batch.map((p) => ({
		merchantKey: p.merchantKey,
		exampleDescription: p.exampleDescription,
		txCount: p.txCount,
		avgAmount: p.avgAmount,
		monthsActive: p.monthsActive,
		cv: p.cv
	})),
	null,
	0
)}

Returner JSON med ett objekt per handlende i samma rekkefølge:
{ "classifications": [{ "merchantKey", "category", "subcategory", "label", "emoji", "isFixed" }, ...] }`;

	const response = await openai.chat.completions.create({
		model: 'gpt-4o-mini',
		response_format: { type: 'json_object' },
		messages: [
			{ role: 'system', content: systemPrompt },
			{ role: 'user', content: fewShotInput },
			{ role: 'assistant', content: fewShotOutput },
			{ role: 'user', content: userPrompt }
		],
		temperature: 0.1,
		max_tokens: 4000
	});

	const raw = response.choices[0]?.message?.content ?? '{}';
	let parsed: { classifications?: MerchantClassification[] };
	try {
		parsed = JSON.parse(raw);
	} catch {
		console.error('[spending-analyzer] Failed to parse LLM response:', raw);
		return [];
	}

	return (parsed.classifications ?? []).filter(
		(c) => c.merchantKey && c.category && c.label
	);
}

// ─── LLM: generate human-readable insights ───────────────────────────────────

async function generateInsights(
	profiles: Array<{
		merchantKey: string;
		exampleDescription: string;
		totalAmount: number;
		avgMonthlyAmount: number;
		txCount: number;
		monthsActive: number;
		cv: number;
		firstMonth: string;
		lastMonth: string;
		mappedCategory: string;
		mappedLabel: string;
		mappedIsFixed: boolean;
	}>,
	totalTxCount: number
): Promise<string[]> {
	// Build a compact summary for the LLM
	const fixedTotal = profiles.filter((p) => p.mappedIsFixed).reduce((s, p) => s + p.totalAmount, 0);
	const variableTotal = profiles.filter((p) => !p.mappedIsFixed).reduce((s, p) => s + p.totalAmount, 0);

	// Top 20 by total amount for insight context
	const top20 = profiles.slice(0, 20).map((p) => ({
		label: p.mappedLabel,
		category: p.mappedCategory,
		totalAmount: p.totalAmount,
		avgMonthly: p.avgMonthlyAmount,
		txCount: p.txCount,
		monthsActive: p.monthsActive,
		isFixed: p.mappedIsFixed
	}));

	const prompt = `Analyser disse norske banktransaksjonsdataene og generer 4-6 korte, konkrete innsikter på norsk.

Totalt ${totalTxCount} transaksjoner. Faste utgifter: ${Math.round(fixedTotal / 1000)}k NOK. Variable: ${Math.round(variableTotal / 1000)}k NOK.

Topp mottakere (siste 13 mnd):
${JSON.stringify(top20, null, 0)}

Regler for innsikter:
- Nevn konkrete tall i NOK
- Identifiser mønstre som prosjekter, sesongvariasjoner, uvanlige utgifter
- Vurder "faste vs variable"-balansen
- Legg merke til om noen kategorier dominerer uventet
- Hvert punkt skal starte med en emoji
- Maks 1 setning per punkt

Returner JSON: { "insights": ["...", "...", ...] }`;

	try {
		const response = await openai.chat.completions.create({
			model: 'gpt-4o-mini',
			response_format: { type: 'json_object' },
			messages: [{ role: 'user', content: prompt }],
			temperature: 0.4,
			max_tokens: 600
		});

		const raw = response.choices[0]?.message?.content ?? '{}';
		const parsed = JSON.parse(raw);
		return parsed.insights ?? [];
	} catch (e) {
		console.error('[spending-analyzer] Insights generation failed:', e);
		return [];
	}
}
